* U - URBAN, R - RURAL, I - INTERSTATE, L - LOCAL, T - TOTAL, F -FREEWAY
* CAP - CAPITAL, MNT - MAINTENANCE
* MIL - MILES , +4  greater than 4 lanes, -4 less than or equal to four
* PASSVEH - % Passenger Vehiles
* TRUSING - % Single Truck
* TRUCOMB - % Combination Truck
* VMT - Vehicle Miles Traveled
* ALASKA NEWYORK CALIFORN SOUTHEAST MIDWEST NORTHEAST - Dummies
* STADMH - State Administered Highways
* LADMRD - Locally Administered Roads
* FEDROAD - Federally Administered Roads
data free file = "G:\BERKELEY\WORK\HIGHWAY\HIGHWAY2.TXT" / State (a)
   CAPUI   CAPUL   CAPUT   MNTUI 
   MNTUL   MNTUT   CAPRI   CAPRL
   CAPRT   MNTRI   MNTRL   MNTRT
   CAPTI   CAPTL   CAPTT   MNTTI
   MNTTL   MNTTT   MILRI   MILRL
   MILRT   MILUI   MILUF   MILUL
   MILUT   UMIL+4    UMIL-4   RMIL+4
   RMIL-4    RPASSVEH   RTRUSING   RTRUCOM
   UPASSVEH  UTRUSING   UTRUCOMB   ALASKA
   NEWYORK     CALIFORN   SOUTHEAS   MIDWEST
   NORTHEAS   VMTRI   VMTRL   VMTRT
   VMTUI   VMTUF   VMTUL   VMTUT
   CSTADMH   CLADMRD   CFEDROAD   CTAL
   MSTADMH   MLADMRD   MREDROAD   MTAL
   ADM_MISC    LAW_SAFE   INTEREST   BONDRET  
   TDISB   MILRI^2 
save outfile='G:\BERKELEY\WORK\HIGHWAY\HIGHWAY2.X'.
get file='G:\BERKELEY\WORK\HIGHWAY\HIGHWAY2.X'.
regression vars= MNTRI MILRI RMIL+4 RTRUCOM RTRUSING 
   NEWYORK CALIFORN SOUTHEAS MIDWEST NORTHEAS ALASKA VMTRI
  /dependent=MNTRI
  /method=enter.
